#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh --material
picom --experimental-backends --backend glx &
feh --bg-scale /home/sam/dotfiles/wallpaper3.jpg
nm-applet &
dunst &
flameshot &


bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          18
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#576173"
bspc config normal_border_color "#353b45"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
